config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :discussions do
    resources :posts, except: [:index], module: :discussions

    collection do
      get 'category/:id', to: 'categories/discussions#index', as: :category
    end

    resources :notifications, only: :create, module: :discussions
  end
  root 'main#index'
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  belongs_to :category, counter_cache: true, touch: true

  delegate :name, prefix: :category, to: :category, allow_nil: true
  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :users, through: :posts
  has_many :discussion_subscriptions, dependent: :destroy
  has_many :optin_subscribers, -> { where(discussion_subscriptions: { subscription_type: :optin }) },
           through: :discussion_subscriptions,
           source: :user
  has_many :optout_subscribers, -> { where(discussion_subscriptions: { subscription_type: :optout }) },
           through: :discussion_subscriptions,
           source: :user
  accepts_nested_attributes_for :posts

  scope :discussions_order, -> { order(pinned: :desc, updated_at: :desc) }

  broadcasts_to :category, inserts_by: :prepend

  after_create_commit -> { broadcast_prepend_to 'discussions' }
  after_update_commit -> { broadcast_replace_to 'discussions' }
  after_destroy_commit -> { broadcast_remove_to 'discussions' }

  def to_param
    "#{id}-#{name.downcase.to_s[0..100]}".parameterize
  end

  def subscribed_users
    (users + optin_subscribers).uniq - optout_subscribers
  end

  def subscription_for(user)
    return nil if user.nil?

    discussion_subscriptions.find_by(user_id: user.id)
  end

  def toggle_subscription(user)
    if (subscription = subscription_for(user))
      subscription.toggle!
    elsif posts.where(user_id: user.id).any?
      discussion_subscriptions.create(user_id: user, subscription_type: 'optout')
    else
      discussion_subscriptions.create(user_id: user, subscription_type: 'optin')
    end
  end

  def subscribed?(user)
    return false if user.nil?

    if subscription = subscription_for(user)
      subscription.subscription_type == 'optin'
    else
      posts.where(user_id: user.id).any?
    end
  end

  def subscribed_reason(user)
    return "You're not receiving notifications from this thread" if user.nil?

    if subscription = subscription_for(user)
      if subscription.subscription_type == 'optout'
        "You're ignoring this thread."
      elsif subscription.subscription_type == 'optin'
        "You're receiving notifications because you've subscribed to this thread."
      end
    elsif posts.where(user_id: user.id).any?
      "You're receiving notifications because you've posted in this thread."
    else
      "You're not receiving notifications from this thread"
    end
  end
end

app/controllers/categories/discussions_controller.rb
module Categories
  class DiscussionsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_category

    def index
      @pagy, @discussions = pagy(@category.discussions.discussions_order)
      render 'discussions/index'
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end
  end
end

app/controllers/discussions/notifications_controller.rb
module Discussions
  class NotificationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion

    def create
      @discussion.toggle_subscription(Current.user)
      redirect_to @discussion
    end

    private

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end
  end
end

app/controllers/discussions/posts_controller.rb
module Discussions
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion
    before_action :set_post, except: %i[create index]

    def show; end
    def edit; end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post.discussion, notice: 'Post updated ' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def create
      @post = @discussion.posts.new(post_params)

      respond_to do |format|
        if @post.save
          if params.dig('post', 'redirect').present?
            @pagy, @posts = pagy(@discussion.posts.order(created_at: :desc))
            format.html do
              redirect_to discussion_path(@discussion, page: @pagy.last), notice: 'Post was successfully created '
            end
          else
            @post = @discussion.posts.new
            format.turbo_stream
          end
        else
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.delete
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@post) }
        format.html { redirect_to @post.discussion, notice: 'Post was successfully deleted ' }
      end
    end

    private

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end

    def set_post
      @post = @discussion.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body)
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: %i[show edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def index
    @pagy, @discussions = pagy(Discussion.includes(:category).discussions_order)
  end

  def show
    @pagy, @posts = pagy(@discussion.posts.includes(:user, :rich_text_body).order(created_at: :asc))
    @new_post = @discussion.posts.new
  end

  def new
    @discussion = Discussion.new
    @discussion.posts.new
  end

  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion created successfully' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @discussion.update(discussion_params)

        DiscussionBroadcaster.new(@discussion).broadcast!
        format.html { redirect_to @discussion, notice: 'Discussion updated' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @discussion.destroy!
    respond_to do |format|
      format.html { redirect_to discussions_path, notice: 'Discussion removed' }
    end
  end

  private

  def discussion_params
    params.require(:discussion).permit(:name, :category_id, :pinned, :closed, posts_attributes: :body)
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

  def not_found
    flash[:notice] = 'The discussion you tried to access does not exist. It may have been deleted'
    redirect_to discussions_path
  end
end

app/views/discussions/_discussion.html.erb
<div id="<%= dom_id(discussion) %>">
  <h2><%= link_to discussion.name, discussion%></h2>
  Pinned: <%= discussion.pinned%>   |   Clossed: <%= discussion.closed%> <br>
  Posted in: <%= discussion.category_name%>   |   Posts: <%= discussion.posts_count%>
  <div>
    <%= link_to "Edit", edit_discussion_path(discussion), class: "" %> |
    <%= link_to "Delete", discussion, data: {turbo_method: :delete, turbo_confirm: "Are you sure? This cannot be undone"} %>
  </div>
</div>

app/views/discussions/_form.html.erb
<%= form_with(model: discussion) do |form| %>
  <% if discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discussion.errors.count, "error") %> prevented this discussion from being saved:</h2>
      <ul>
        <% discussion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, placeholder: "How do I...?", class: "form-control" %>
  </div>
    
<div class="mb-3">
  <%= form.label :category_id, class: "form-label" %>
  <%= form.collection_select :category_id, Category.sorted, :id, :name, {include_blank: "Pick a category"}, {autofocus: false, class: "form-control"} %>
</div>

  <div class="mb-3">
    <%= form.label :pinned, class: "form-label" %>
    <%= form.check_box :pinned %>
  </div>
  <div class="mb-3">
    <%= form.label :closed, class: "form-label" %>
    <%= form.check_box :closed %>
  </div>

  <% if discussion.new_record? %>
    <%= form.fields_for :posts do  |p| %>
    <div class="mb-3">
      <%= p.rich_text_area :body, placeholder: "Kickoff the discussion"%>
    </div>
    
    <% end %>
  
  <% end %>
  
  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/discussions/_header.html.erb
<%= turbo_frame_tag dom_id(discussion) do %>
  <div class="d-flex align-items-center justify-content-between">
    <div>
      <h1><%= discussion.name %></h1>
      <span class="text-muted fs-6">
        <% if discussion.pinned %>
          <span class="badge rounded-pill bg-info">Pinned</span>
        <% end %>
        <% if discussion.closed %>
          <span class="badge rounded-pill text-danger">Closed</span>
        <% end %>
      </span>
    </div>
    <div>
      <%= link_to "Edit", edit_discussion_path(discussion) %> |
      <%= link_to "Delete", discussion, data: {turbo_method: :delete, turbo_frame: "_top"} %>
    </div>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Edit Discussion</h1>
<%= turbo_frame_tag dom_id(@discussion) do %>
  <%= render "form", discussion: @discussion %>
  <%=link_to 'Cancel', @discussion %>
<%end%>

app/views/discussions/index.html.erb
<% if @category.present? %>
  <%= turbo_stream_from @category %>
<% else %>
  <%= turbo_stream_from 'discussions' %>
<% end %>
<div class="d-flex justify-content-between align-items-center">
  <h1>Discussions</h1>
  <%= link_to 'New Discusion', new_discussion_path, class: "btn btn-primary" %>
</div>
<div class="row mt-4">
  <div class="col-3">
    <%= turbo_stream_from 'categories'%>
    <h5>Categories</h5>
    <div id="categories">
      <%= render(partial: "categories/category", collection: Category.sorted) %>
    </div>
  </div>
  <div class="col">
    <% if @category %>
      <h4>Viewing discussions in <%= @category.name %></h4>
    <% end %>
    <% if params[:page].blank? || params[:page].eql?('1') %>
      <div id="discussions"></div>
    <% end %>
    <%= render partial: "discussions/discussion", collection: @discussions %>
    <hr class="mb-4">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/discussions/new.html.erb
<h1>New Discussion</h1>
<%= render "form", discussion: @discussion %>

app/views/discussions/show.html.erb
<%= turbo_stream_from @discussion %>
<%= render( 'discussions/header', discussion: @discussion ) %>
<div class="mt-4">
  <%= render partial: "discussions/posts/post", collection: @posts %>
  <% if @pagy.page == @pagy.last %>
    <div id="posts" class="mt-4"></div>
  <% end %>
</div>
<hr class="my-4">
<%== pagy_bootstrap_nav(@pagy)%>
<hr class="my-4">
<%= turbo_frame_tag "discussion_notification_status" do %>
  <%= render('discussions/notifications/status', discussion: @discussion, user: Current.user) %>
<% end %>
<hr class="my-4">
<div id="<%=dom_id(@new_post)%>">
  <%= render "discussions/posts/form", post: @new_post, redirect: @pagy.page != @pagy.last %>
</div>