config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :discussions do
    resources :posts, except: [:index], module: :discussions

    collection do
      get 'category/:id', to: 'categories/discussions#index', as: :category
    end

    resources :notifications, only: :create, module: :discussions
  end
  root 'main#index'
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  belongs_to :category, counter_cache: true, touch: true

  delegate :name, prefix: :category, to: :category, allow_nil: true
  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :users, through: :posts
  has_many :discussion_subscriptions, dependent: :destroy
  has_many :optin_subscribers, -> { where(discussion_subscriptions: { subscription_type: :optin }) },
           through: :discussion_subscriptions,
           source: :user
  has_many :optout_subscribers, -> { where(discussion_subscriptions: { subscription_type: :optout }) },
           through: :discussion_subscriptions,
           source: :user
  accepts_nested_attributes_for :posts

  scope :discussions_order, -> { order(pinned: :desc, updated_at: :desc) }

  broadcasts_to :category, inserts_by: :prepend

  after_create_commit -> { broadcast_prepend_to 'discussions' }
  after_update_commit -> { broadcast_replace_to 'discussions' }
  after_destroy_commit -> { broadcast_remove_to 'discussions' }

  def to_param
    "#{id}-#{name.downcase.to_s[0..100]}".parameterize
  end

  def subscribed_users
    (users + optin_subscribers).uniq - optout_subscribers
  end

  def subscription_for(user)
    return nil if user.nil?

    discussion_subscriptions.find_by(user_id: user.id)
  end

  def toggle_subscription(user)
    if (subscription = subscription_for(user))
      subscription.toggle!
    elsif posts.where(user_id: user.id).any?
      discussion_subscriptions.create(user_id: user, subscription_type: 'optout')
    else
      discussion_subscriptions.create(user_id: user, subscription_type: 'optin')
    end
  end

  def subscribed?(user)
    return false if user.nil?

    if subscription = subscription_for(user)
      subscription.subscription_type == 'optin'
    else
      posts.where(user_id: user.id).any?
    end
  end

  def subscribed_reason(user)
    return "You're not receiving notifications from this thread" if user.nil?

    if subscription = subscription_for(user)
      if subscription.subscription_type == 'optout'
        "You're ignoring this thread."
      elsif subscription.subscription_type == 'optin'
        "You're receiving notifications because you've subscribed to this thread."
      end
    elsif posts.where(user_id: user.id).any?
      "You're receiving notifications because you've posted in this thread."
    else
      "You're not receiving notifications from this thread"
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :discussion, counter_cache: true, touch: true
  belongs_to :user, default: -> { Current.user }
  has_rich_text :body
  validates :body, presence: true

  after_create_commit -> { broadcast_append_to discussion, partial: 'discussions/posts/post', locals: { post: self } }
  after_update_commit -> { broadcast_replace_to discussion, partial: 'discussions/posts/post', locals: { post: self } }
  after_destroy_commit -> { broadcast_remove_to discussion }
end

app/controllers/categories/discussions_controller.rb
module Categories
  class DiscussionsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_category

    def index
      @pagy, @discussions = pagy(@category.discussions.discussions_order)
      render 'discussions/index'
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end
  end
end

app/controllers/discussions/notifications_controller.rb
module Discussions
  class NotificationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion

    def create
      @discussion.toggle_subscription(Current.user)
      redirect_to @discussion
    end

    private

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end
  end
end

app/controllers/discussions/posts_controller.rb
module Discussions
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion
    before_action :set_post, except: %i[create index]

    def show; end
    def edit; end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post.discussion, notice: 'Post updated ' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def create
      @post = @discussion.posts.new(post_params)

      respond_to do |format|
        if @post.save
          if params.dig('post', 'redirect').present?
            @pagy, @posts = pagy(@discussion.posts.order(created_at: :desc))
            format.html do
              redirect_to discussion_path(@discussion, page: @pagy.last), notice: 'Post was successfully created '
            end
          else
            @post = @discussion.posts.new
            format.turbo_stream
          end
        else
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.delete
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@post) }
        format.html { redirect_to @post.discussion, notice: 'Post was successfully deleted ' }
      end
    end

    private

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end

    def set_post
      @post = @discussion.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body)
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: %i[show edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def index
    @pagy, @discussions = pagy(Discussion.includes(:category).discussions_order)
  end

  def show
    @pagy, @posts = pagy(@discussion.posts.includes(:user, :rich_text_body).order(created_at: :asc))
    @new_post = @discussion.posts.new
  end

  def new
    @discussion = Discussion.new
    @discussion.posts.new
  end

  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion created successfully' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @discussion.update(discussion_params)

        DiscussionBroadcaster.new(@discussion).broadcast!
        format.html { redirect_to @discussion, notice: 'Discussion updated' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @discussion.destroy!
    respond_to do |format|
      format.html { redirect_to discussions_path, notice: 'Discussion removed' }
    end
  end

  private

  def discussion_params
    params.require(:discussion).permit(:name, :category_id, :pinned, :closed, posts_attributes: :body)
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

  def not_found
    flash[:notice] = 'The discussion you tried to access does not exist. It may have been deleted'
    redirect_to discussions_path
  end
end

app/views/discussions/posts/_form.html.erb
<%=turbo_frame_tag "post_form", target: "_top"  do %>
  <% if post.discussion.closed? && post.new_record? %>
    <div class="alert alert-secondary fw-bold">
      This discussion is currently locked.
    </div>
  <%else%>
    <%= form_with(model: [post.discussion, post]) do |form| %>
      <% if post.errors.any? %>
        <div id="error_explantion">
          <h2>
            <%= pluralize(post.errors.count, "error") %>
            prohibited this post from being saved:
          </h2>
          <ul>
            <% post.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mb-3">
        <%= form.rich_text_area :body, placeholder: "Add your comment" %>
      </div>
      <% if local_assigns[:redirect] %>
        <%=form.hidden_field :redirect, value: true%>
      <% end %>
      <div class="mb-3">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/discussions/posts/_header.html.erb
<h4 class="card-title"><%= post.user.username %></h4>
<h6 class="card-subtitle mb-3 text-muted border-bottom pb-3">Posted on: <%= post.created_at %></h6>

app/views/discussions/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
  <div class="card my-4">
    <div class="card-body">
      <%= render(partial: "discussions/posts/header", locals: { post: post }) %>
      <%= post.body %>
    </div>
    <% if action_name.nil? %>
      <%# lazy load controls because it's being broadcasted %>
      <%= turbo_frame_tag "post_actions", src: discussion_post_path(post.discussion, post) do %>
        <div class="card-footer"></div>
      <% end %>
    <% else %>
      <%= turbo_frame_tag 'post_actions' do %>
        <% if Current.user == post.user || Current.user.admin? %>
          <div class="card-footer">
            <%= link_to 'Edit', edit_discussion_post_path(post.discussion, post), data: {turbo_frame: dom_id(post)} %> | 
            <%= link_to 'Delete', discussion_post_path(post.discussion, post), data: { turbo_method: :delete, turbo_frame: "_top" } %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/discussions/posts/create.turbo_stream.erb
<%= turbo_stream.replace "post_form" do %>
  <%= render partial: "discussions/posts/form", formats: :html, locals: { post: @post, redirect: true } %>
<% end %>

app/views/discussions/posts/edit.html.erb
<h1>Edit post</h1>
<%= turbo_frame_tag dom_id(@post) do %>
  <div class="card my-4">
    <div class="card-body">
      <%= render(partial: "discussions/posts/header", locals: { post: @post }) %>
      <%= render("form", post: @post) %>
      <%= link_to 'Back', discussion_post_path(@post.discussion, @post) %>
    </div>
  </div>
<% end %>

app/views/discussions/posts/show.html.erb
<%= render partial: "discussions/posts/post", locals: { post: @post } %>